packages: []
ignoredBuiltDependencies:
  - core-js
minimumReleaseAge: 2880
onlyBuiltDependencies:
  - electron
  - electron-mksnapshot
  - electron-winstaller
  - leveldown
overrides:
  node-gyp: ^11.5.0
